/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.yildirimbayrakci.lms;

import com.yildirimbayrakci.entity.Account;
import com.yildirimbayrakci.enums_and_constants.AccountType;
import com.yildirimbayrakci.util.HibernateUtils;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author YILDIRIM
 */
public class AdminScreen extends javax.swing.JFrame {

    private static AdminScreen adminScreen;
    // Internal frames
    private final BookManagement bookManagement;
    private final UserManagement userManagement;
    private  Options options;
    private final History report;

    private int x, y;
    private static Account account;
    private final Color passive, active;
    private final boolean authorized;

    /**
     * Creates new form AdminScreen
     */
    private AdminScreen(Account account) {
        AdminScreen.account = account;
        initComponents();
        authorized = account.getType() == AccountType.ADMIN;
        
        // initiating internal frames.
        bookManagement = new BookManagement(account);
        userManagement = new UserManagement();
        options = new Options(bookManagement, userManagement);
        report = new History();

        
        jDesktopPane.add(bookManagement).setVisible(true);
        active = new Color(222, 222, 222);
        passive = new Color(153, 255, 102);
        jPanel_bookPanel.setBackground(active);
        
        jLabel_welcome.setText("Hoşgeldiniz, " + account.getFirstName() + " " + account.getLastName());
        
        if(!authorized){
            jPanel_optionsPanel.setVisible(false);
            options = null;
        }
            
       
    }

    public static AdminScreen getInstance(Account account) {
        if (adminScreen == null) {
            adminScreen = new AdminScreen(account);
        }
        return adminScreen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_topFrame = new javax.swing.JPanel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel_welcome = new javax.swing.JLabel();
        jButton_exitAccount = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel_left = new javax.swing.JPanel();
        jPanel_bookPanel = new javax.swing.JPanel();
        jLabel_BookText = new javax.swing.JLabel();
        jPanel_userPanel = new javax.swing.JPanel();
        jLabel_UserText = new javax.swing.JLabel();
        jPanel_optionsPanel = new javax.swing.JPanel();
        jLabel_SettingsText = new javax.swing.JLabel();
        jPanel_report = new javax.swing.JPanel();
        jLabel_HistoryText = new javax.swing.JLabel();
        jDesktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_topFrame.setBackground(new java.awt.Color(0, 0, 0));
        jPanel_topFrame.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_topFrameMouseDragged(evt);
            }
        });
        jPanel_topFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_topFrameMousePressed(evt);
            }
        });

        jLabel_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Close_white.png"))); // NOI18N
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });

        jLabel_welcome.setForeground(new java.awt.Color(255, 255, 255));

        jButton_exitAccount.setBackground(new java.awt.Color(51, 153, 0));
        jButton_exitAccount.setForeground(new java.awt.Color(255, 255, 255));
        jButton_exitAccount.setText("Çıkış Yap");
        jButton_exitAccount.setContentAreaFilled(false);
        jButton_exitAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_exitAccount.setFocusPainted(false);
        jButton_exitAccount.setOpaque(true);
        jButton_exitAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exitAccountActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_topFrameLayout = new javax.swing.GroupLayout(jPanel_topFrame);
        jPanel_topFrame.setLayout(jPanel_topFrameLayout);
        jPanel_topFrameLayout.setHorizontalGroup(
            jPanel_topFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_topFrameLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 673, Short.MAX_VALUE)
                .addComponent(jButton_exitAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_exit)
                .addGap(13, 13, 13))
        );
        jPanel_topFrameLayout.setVerticalGroup(
            jPanel_topFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_topFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_topFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_welcome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton_exitAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel_topFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 50));

        jPanel_left.setBackground(new java.awt.Color(51, 153, 0));

        jPanel_bookPanel.setBackground(new java.awt.Color(222, 222, 222));
        jPanel_bookPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_bookPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_bookPanelMouseClicked(evt);
            }
        });

        jLabel_BookText.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel_BookText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/book.png"))); // NOI18N
        jLabel_BookText.setText("   KİTAP YÖNETİM");

        javax.swing.GroupLayout jPanel_bookPanelLayout = new javax.swing.GroupLayout(jPanel_bookPanel);
        jPanel_bookPanel.setLayout(jPanel_bookPanelLayout);
        jPanel_bookPanelLayout.setHorizontalGroup(
            jPanel_bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_BookText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_bookPanelLayout.setVerticalGroup(
            jPanel_bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_bookPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_BookText)
                .addContainerGap())
        );

        jPanel_userPanel.setBackground(new java.awt.Color(153, 255, 102));
        jPanel_userPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_userPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_userPanelMouseClicked(evt);
            }
        });

        jLabel_UserText.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel_UserText.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_UserText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/study.png"))); // NOI18N
        jLabel_UserText.setText("   KULLANICI YÖNETİM");

        javax.swing.GroupLayout jPanel_userPanelLayout = new javax.swing.GroupLayout(jPanel_userPanel);
        jPanel_userPanel.setLayout(jPanel_userPanelLayout);
        jPanel_userPanelLayout.setHorizontalGroup(
            jPanel_userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_UserText, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_userPanelLayout.setVerticalGroup(
            jPanel_userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_UserText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_optionsPanel.setBackground(new java.awt.Color(153, 255, 102));
        jPanel_optionsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_optionsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_optionsPanelMouseClicked(evt);
            }
        });

        jLabel_SettingsText.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel_SettingsText.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_SettingsText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/settings (1).png"))); // NOI18N
        jLabel_SettingsText.setText("   HAKKINDA");

        javax.swing.GroupLayout jPanel_optionsPanelLayout = new javax.swing.GroupLayout(jPanel_optionsPanel);
        jPanel_optionsPanel.setLayout(jPanel_optionsPanelLayout);
        jPanel_optionsPanelLayout.setHorizontalGroup(
            jPanel_optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_optionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_SettingsText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_optionsPanelLayout.setVerticalGroup(
            jPanel_optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_optionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_SettingsText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_report.setBackground(new java.awt.Color(153, 255, 102));
        jPanel_report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_reportMouseClicked(evt);
            }
        });

        jLabel_HistoryText.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel_HistoryText.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_HistoryText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/book 2.png"))); // NOI18N
        jLabel_HistoryText.setText("   GEÇMİŞ");

        javax.swing.GroupLayout jPanel_reportLayout = new javax.swing.GroupLayout(jPanel_report);
        jPanel_report.setLayout(jPanel_reportLayout);
        jPanel_reportLayout.setHorizontalGroup(
            jPanel_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_reportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_HistoryText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_reportLayout.setVerticalGroup(
            jPanel_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_reportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_HistoryText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_leftLayout = new javax.swing.GroupLayout(jPanel_left);
        jPanel_left.setLayout(jPanel_leftLayout);
        jPanel_leftLayout.setHorizontalGroup(
            jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_bookPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_leftLayout.setVerticalGroup(
            jPanel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_leftLayout.createSequentialGroup()
                .addComponent(jPanel_bookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel_userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel_report, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel_optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 510));

        jDesktopPane.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 930, 510));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Başkent University MIS - TBF415 - Project Management - Scrum Project - Grup 7                                                                                                                                                ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1170, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_bookPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_bookPanelMouseClicked
        jDesktopPane.removeAll();
        jDesktopPane.add(bookManagement).setVisible(true);
        jPanel_bookPanel.setBackground(active);
        jPanel_optionsPanel.setBackground(passive);
        jPanel_userPanel.setBackground(passive);
        jPanel_report.setBackground(passive);

        jLabel_BookText.setForeground(Color.black);
        jLabel_HistoryText.setForeground(Color.white);
        jLabel_UserText.setForeground(Color.white);
        jLabel_SettingsText.setForeground(Color.white);


    }//GEN-LAST:event_jPanel_bookPanelMouseClicked

    private void jPanel_userPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_userPanelMouseClicked
        jDesktopPane.removeAll();
        if(authorized)
            jDesktopPane.add(userManagement).setVisible(true);
        else
            jDesktopPane.add(new UserManagement_user(account)).setVisible(true);
        jPanel_bookPanel.setBackground(passive);
        jPanel_optionsPanel.setBackground(passive);
        jPanel_userPanel.setBackground(active);
        jPanel_report.setBackground(passive);

        jLabel_BookText.setForeground(Color.white);
        jLabel_HistoryText.setForeground(Color.white);
        jLabel_UserText.setForeground(Color.black);
        jLabel_SettingsText.setForeground(Color.white);
    }//GEN-LAST:event_jPanel_userPanelMouseClicked

    private void jPanel_optionsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_optionsPanelMouseClicked
        jDesktopPane.removeAll();
        jDesktopPane.add(options).setVisible(true);
        jPanel_bookPanel.setBackground(passive);
        jPanel_optionsPanel.setBackground(active);
        jPanel_userPanel.setBackground(passive);
        jPanel_report.setBackground(passive);

        jLabel_BookText.setForeground(Color.white);
        jLabel_HistoryText.setForeground(Color.white);
        jLabel_UserText.setForeground(Color.white);
        jLabel_SettingsText.setForeground(Color.black);
    }//GEN-LAST:event_jPanel_optionsPanelMouseClicked

    private void jPanel_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_reportMouseClicked
        jDesktopPane.removeAll();
        jDesktopPane.add(report).setVisible(true);
        jPanel_bookPanel.setBackground(passive);
        jPanel_optionsPanel.setBackground(passive);
        jPanel_userPanel.setBackground(passive);
        jPanel_report.setBackground(active);

        jLabel_BookText.setForeground(Color.white);
        jLabel_HistoryText.setForeground(Color.black);
        jLabel_UserText.setForeground(Color.white);
        jLabel_SettingsText.setForeground(Color.white);
    }//GEN-LAST:event_jPanel_reportMouseClicked

    private void jPanel_topFrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_topFrameMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel_topFrameMousePressed

    private void jPanel_topFrameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_topFrameMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_jPanel_topFrameMouseDragged

    private void jButton_exitAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exitAccountActionPerformed
        int answer = CustomDialog.showDialog(this, "Hesabınızdan çıkış yapmak istediğinize emin misiniz?");

        if (answer == JOptionPane.YES_OPTION) {
            setVisible(false);
            
            AdminScreen.adminScreen = null;
            dispose();
            new LoginScreen().setVisible(true);

        }
    }//GEN-LAST:event_jButton_exitAccountActionPerformed

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked

        int answer = CustomDialog.showDialog(this, "Programdan çıkmak istediğinize emin misiniz?");
        if (answer == JOptionPane.YES_OPTION) {
            HibernateUtils.getSessionFactory().close();
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel_exitMouseClicked

    public Account getAccount() {
        return account;
    }

    public static void setAccount(Account account) {
        AdminScreen.account = account;
        
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminScreen(null).setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_exitAccount;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_BookText;
    private javax.swing.JLabel jLabel_HistoryText;
    private javax.swing.JLabel jLabel_SettingsText;
    private javax.swing.JLabel jLabel_UserText;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_welcome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_bookPanel;
    private javax.swing.JPanel jPanel_left;
    private javax.swing.JPanel jPanel_optionsPanel;
    private javax.swing.JPanel jPanel_report;
    private javax.swing.JPanel jPanel_topFrame;
    private javax.swing.JPanel jPanel_userPanel;
    // End of variables declaration//GEN-END:variables

    public JPanel getjPanel_bookPanel() {
        return jPanel_bookPanel;
    }

    public void setjPanel_bookPanel(JPanel jPanel_bookPanel) {
        this.jPanel_bookPanel = jPanel_bookPanel;
    }

    public JPanel getjPanel_left() {
        return jPanel_left;
    }

    public void setjPanel_left(JPanel jPanel_left) {
        this.jPanel_left = jPanel_left;
    }

    public JPanel getjPanel_topFrame() {
        return jPanel_topFrame;
    }

    public void setjPanel_topFrame(JPanel jPanel_topFrame) {
        this.jPanel_topFrame = jPanel_topFrame;
    }

    public JPanel getjPanel_userPanel() {
        return jPanel_userPanel;
    }

    public void setjPanel_userPanel(JPanel jPanel_userPanel) {
        this.jPanel_userPanel = jPanel_userPanel;
    }

    public JPanel getjPanel_optionsPanel() {
        return jPanel_optionsPanel;
    }

    public void setjPanel_optionsPanel(JPanel jPanel_optionsPanel) {
        this.jPanel_optionsPanel = jPanel_optionsPanel;
    }

}
