package com.yildirimbayrakci.lms;

import com.yildirimbayrakci.entity.Account;
import com.yildirimbayrakci.util.HibernateUtils;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.mindrot.jbcrypt.BCrypt;

/**
 * @author YILDIRIM
 */
public class LoginScreen extends javax.swing.JFrame {

    private static LoginScreen loginScreen;
    private int x, y;
    private SessionFactory sessionFactory;
    private final Color active, passive;

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        active = new Color(57, 113, 177);
        passive = new Color(51, 52, 54);
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_loginScreen = new javax.swing.JPanel();
        jLabel_passwordText = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel_login_message = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jLabel_usernameText = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_exit_text = new javax.swing.JLabel();
        jLabel_loading = new javax.swing.JLabel();
        button_login = new javax.swing.JButton();
        jCheckBox_showPassword = new javax.swing.JCheckBox();

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel_loginScreen.setBackground(new java.awt.Color(29, 29, 29));
        jPanel_loginScreen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_loginScreenMouseDragged(evt);
            }
        });
        jPanel_loginScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_loginScreenMousePressed(evt);
            }
        });
        jPanel_loginScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_passwordText.setForeground(new java.awt.Color(51, 52, 54));
        jLabel_passwordText.setText("Şifre");
        jPanel_loginScreen.add(jLabel_passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jTextField_username.setBackground(new java.awt.Color(29, 29, 29));
        jTextField_username.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_username.setToolTipText("");
        jTextField_username.setBorder(null);
        jTextField_username.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusGained(evt);
            }
        });
        jTextField_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_usernameKeyReleased(evt);
            }
        });
        jPanel_loginScreen.add(jTextField_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 220, 20));

        jLabel_login_message.setForeground(Color.GREEN);
        jLabel_login_message.setText("Hoşgeldiniz.");
        jPanel_loginScreen.add(jLabel_login_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 160, 30));

        jPasswordField_password.setBackground(new java.awt.Color(29, 29, 29));
        jPasswordField_password.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField_password.setBorder(null);
        jPasswordField_password.setCaretColor(new java.awt.Color(255, 255, 255));
        jPasswordField_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_passwordFocusGained(evt);
            }
        });
        jPasswordField_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField_passwordKeyReleased(evt);
            }
        });
        jPanel_loginScreen.add(jPasswordField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 220, 20));

        jLabel_usernameText.setForeground(new java.awt.Color(43, 87, 151));
        jLabel_usernameText.setText("Kullanıcı ID");
        jPanel_loginScreen.add(jLabel_usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));
        jPanel_loginScreen.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 118, 220, 10));
        jPanel_loginScreen.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 220, -1));

        jLabel_exit_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_exit_text.setForeground(new java.awt.Color(43, 87, 151));
        jLabel_exit_text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Close_blue.png"))); // NOI18N
        jLabel_exit_text.setToolTipText("Kapat");
        jLabel_exit_text.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exit_textMouseClicked(evt);
            }
        });
        jPanel_loginScreen.add(jLabel_exit_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 30, 20));

        jLabel_loading.setVisible(false);
        jLabel_loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/loading_spinner.gif"))); // NOI18N
        jPanel_loginScreen.add(jLabel_loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        button_login.setBackground(new java.awt.Color(126, 56, 120));
        button_login.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        button_login.setForeground(new java.awt.Color(255, 255, 255));
        button_login.setText("Giriş Yap");
        button_login.setContentAreaFilled(false);
        button_login.setOpaque(true);
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });
        jPanel_loginScreen.add(button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 220, 40));

        jCheckBox_showPassword.setBackground(new java.awt.Color(29, 29, 29));
        jCheckBox_showPassword.setForeground(new java.awt.Color(153, 153, 0));
        jCheckBox_showPassword.setText(" Şifreyi göster");
        jCheckBox_showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_showPasswordActionPerformed(evt);
            }
        });
        jPanel_loginScreen.add(jCheckBox_showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        getContentPane().add(jPanel_loginScreen, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(328, 417));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cleans the JTextField and JPasswordField in LoginScreen
     */
    public void cleanFields() {
        jTextField_username.setText("");
        jPasswordField_password.setText("");
        jLabel_login_message.setText("Hoşgeldiniz.");
        jLabel_loading.setVisible(false);
    }

    private void jTextField_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusGained
        jLabel_passwordText.setForeground(passive);
        jLabel_usernameText.setForeground(active);
    }//GEN-LAST:event_jTextField_usernameFocusGained

    private void jLabel_exit_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exit_textMouseClicked
        if (sessionFactory != null) {
            sessionFactory.close();
        }
        System.exit(0);
    }//GEN-LAST:event_jLabel_exit_textMouseClicked

    private void jPasswordField_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_passwordFocusGained
        jLabel_passwordText.setForeground(active);
        jLabel_usernameText.setForeground(passive);
    }//GEN-LAST:event_jPasswordField_passwordFocusGained

    private void jPanel_loginScreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_loginScreenMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel_loginScreenMousePressed

    private void jPanel_loginScreenMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_loginScreenMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();

        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_jPanel_loginScreenMouseDragged

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        button_login.setEnabled(false);
        sessionFactory = HibernateUtils.getSessionFactory();
        Session session = null;

        try {
            if (sessionFactory == null) {
                jLabel_login_message.setText("HATA: Veri tabanı bağlantısı başarısız.");
            } else {
                String username = jTextField_username.getText();
                String password = new String(jPasswordField_password.getPassword());

                if (username.equals("")) {
                    jLabel_login_message.setForeground(Color.RED);
                    jLabel_login_message.setText("Lütfen bir kullanıcı adı giriniz.");
                } else if (password.equals("")) {
                    jLabel_login_message.setForeground(Color.RED);
                    jLabel_login_message.setText("Lütfen şifrenizi giriniz.");
                } else {
                    session = sessionFactory.getCurrentSession();

                    session.beginTransaction();

                    Account account = session.get(Account.class, username);

                    session.getTransaction().commit();

                    if (account == null) {
                        jLabel_login_message.setForeground(Color.RED);
                        jLabel_login_message.setText("Kullanıcı bulunamadı.");
                    } else {
                        System.out.println(BCrypt.hashpw(password, BCrypt.gensalt()));
                        System.out.println(account.getPassword());
                        if (BCrypt.checkpw(password, account.getPassword())) {
                            if (null != account.getStatus()) {
                                switch (account.getStatus()) {
                                    case AKTIF:
                                        jLabel_login_message.setForeground(Color.GREEN);
                                        jLabel_login_message.setText("Giriş başarılı.");
                                        jLabel_loading.setVisible(true);

                                        ActionListener al = (ActionEvent ae) -> {

                                            AdminScreen adminScreen = AdminScreen.getInstance(account);
                                            adminScreen.setVisible(true);

                                            setVisible(false);
                                            dispose();
                                        };
                                        Timer timer = new Timer(1200, al);
                                        timer.setRepeats(false);
                                        timer.start();

                                        break;
                                    case IPTAL:
                                        jLabel_login_message.setForeground(Color.RED);
                                        jLabel_login_message.setText("Hesabınız iptal edilmiştir.");
                                        break;
                                    case KARALISTE:
                                        jLabel_login_message.setForeground(Color.RED);
                                        jLabel_login_message.setText("Hesabınız kara listededir.");
                                        break;
                                    default:
                                        break;
                                }
                            }
                        } else {
                            jLabel_login_message.setForeground(Color.RED);
                            jLabel_login_message.setText("Yanlış parola.");
                        }
                    }
                }

            }
        } catch (HibernateException e) {
        } finally {
            if (session != null) {
                session.close();
            }
            button_login.setEnabled(true);

        }
    }//GEN-LAST:event_button_loginActionPerformed

    private void jTextField_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usernameKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            button_login.doClick();
        }
    }//GEN-LAST:event_jTextField_usernameKeyReleased

    private void jPasswordField_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_passwordKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            button_login.doClick();
        }
    }//GEN-LAST:event_jPasswordField_passwordKeyReleased

    private void jCheckBox_showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_showPasswordActionPerformed
                
        
        if(jCheckBox_showPassword.isSelected())
            jPasswordField_password.setEchoChar((char) 0);
        else // ●●●●●
            jPasswordField_password.setEchoChar('●');
        
    }//GEN-LAST:event_jCheckBox_showPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            loginScreen = new LoginScreen();
            loginScreen.setVisible(true);
        });

        Thread thread = new Thread() {
            Timer timer;

            @Override
            public void run() {
                try {

                    SwingUtilities.invokeLater(() -> {
                        timer = new Timer(500, new ActionListener() {
                            int count = 0;

                            @Override
                            public void actionPerformed(ActionEvent ae) {
                                String dot;
                                switch (count % 3) {
                                    case 0:
                                        dot = ".";
                                        break;
                                    case 1:
                                        dot = "..";
                                        break;
                                    default:
                                        dot = "...";
                                        break;
                                }
                                loginScreen.jLabel_login_message.setForeground(new Color(204, 204, 0));
                                loginScreen.jLabel_loading.setVisible(true);
                                loginScreen.jLabel_login_message.setText("Veritabanına bağlanılıyor" + dot);
                                count++;
                            }
                        });
                        timer.start();

                    });

                    HibernateUtils.getSessionFactory();
                    timer.stop();
                    loginScreen.jLabel_loading.setVisible(false);
                    loginScreen.jLabel_login_message.setText("Veritabanına bağlanıldı.");
                    loginScreen.jLabel_login_message.setForeground(Color.GREEN);
                    loginScreen.button_login.setEnabled(true);

                } catch (Exception exc) {
                    timer.stop();
                    loginScreen.jLabel_login_message.setForeground(Color.RED);
                    loginScreen.jLabel_login_message.setText("Bağlantı başarısız.");
                    loginScreen.jLabel_loading.setVisible(false);

                }

            }

        };
        thread.start();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_login;
    private javax.swing.JCheckBox jCheckBox_showPassword;
    private javax.swing.JLabel jLabel_exit_text;
    private javax.swing.JLabel jLabel_loading;
    private javax.swing.JLabel jLabel_login_message;
    private javax.swing.JLabel jLabel_passwordText;
    private javax.swing.JLabel jLabel_usernameText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_loginScreen;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
