/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.yildirimbayrakci.lms;

import com.yildirimbayrakci.util.JavaMail;
import com.yildirimbayrakci.util.Search;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author YILDIRIM
 */
public class Options extends javax.swing.JInternalFrame {

    /**
     * Creates new form Options
     */
    private AdminScreen adminScreen;
    private final BookManagement bookManagement;
    private final UserManagement userManagement;

    public Options(BookManagement bookManagement, UserManagement userManagement) {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bif = (BasicInternalFrameUI) this.getUI();
        bif.setNorthPane(null);

        this.bookManagement = bookManagement;
        this.userManagement = userManagement;
        this.adminScreen = adminScreen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_options = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_totalbook = new javax.swing.JTextField();
        jTextField_bookAvailable = new javax.swing.JTextField();
        jTextField_bookBorrowed = new javax.swing.JTextField();
        jTextField_totalUser = new javax.swing.JTextField();
        jTextField_normalUserCount = new javax.swing.JTextField();
        jTextField_academicUserCount = new javax.swing.JTextField();
        jTextField_adminUserCount = new javax.swing.JTextField();
        jButton_bringIstatistics = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_bookReserved = new javax.swing.JTextField();
        jTextField_bookLost = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(930, 510));

        jPanel_options.setBackground(new java.awt.Color(222, 222, 222));
        jPanel_options.setPreferredSize(new java.awt.Dimension(930, 510));

        jLabel5.setText("Toplam Kitap Sayısı:");

        jLabel6.setText("Toplam Kullanıcı Sayısı:");

        jLabel8.setText("Normal Kullanıcı Sayısı:");

        jLabel9.setText("Mevcut Kitap Sayısı:");

        jLabel10.setText("Ödünç Verilmiş Kitap Sayısı:");

        jLabel11.setText("Öğretim Üyesi Kullanıcı Sayısı:");

        jLabel12.setText("Yönetici Kullanıcı Sayısı:");

        jTextField_totalbook.setEnabled(false);

        jTextField_bookAvailable.setEnabled(false);

        jTextField_bookBorrowed.setEnabled(false);

        jTextField_totalUser.setEnabled(false);

        jTextField_normalUserCount.setEnabled(false);

        jTextField_academicUserCount.setEnabled(false);

        jTextField_adminUserCount.setEnabled(false);

        jButton_bringIstatistics.setText("İstatistikleri Getir");
        jButton_bringIstatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bringIstatisticsActionPerformed(evt);
            }
        });

        jLabel1.setText("Rezerve Kitap Sayısı:");

        jLabel2.setText("Kayıp Kitap Sayısı:");

        jTextField_bookReserved.setEnabled(false);

        jTextField_bookLost.setEnabled(false);

        javax.swing.GroupLayout jPanel_optionsLayout = new javax.swing.GroupLayout(jPanel_options);
        jPanel_options.setLayout(jPanel_optionsLayout);
        jPanel_optionsLayout.setHorizontalGroup(
            jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_optionsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_optionsLayout.createSequentialGroup()
                        .addComponent(jButton_bringIstatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_optionsLayout.createSequentialGroup()
                        .addGroup(jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addGroup(jPanel_optionsLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_bookReserved, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_totalbook, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_bookAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_bookBorrowed, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_bookLost, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117)
                        .addGroup(jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6))
                            .addGroup(jPanel_optionsLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_adminUserCount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_totalUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_normalUserCount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_academicUserCount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(221, Short.MAX_VALUE))))
        );
        jPanel_optionsLayout.setVerticalGroup(
            jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_optionsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_totalbook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_totalUser, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_bookAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_normalUserCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTextField_bookBorrowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jTextField_academicUserCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_optionsLayout.createSequentialGroup()
                        .addGroup(jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_bookReserved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_bookLost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField_adminUserCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jButton_bringIstatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_options, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_options, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_bringIstatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bringIstatisticsActionPerformed
        // TODO add your handling code here:
        
        jTextField_totalbook.setText(Search.bringCounts("totalBooks") + "");
        jTextField_bookAvailable.setText(Search.bringCounts("availableBooks") + "");
        jTextField_bookBorrowed.setText(Search.bringCounts("borrowedBooks") + "");
        jTextField_totalUser.setText(Search.bringCounts("totalUsers") + "");
        jTextField_academicUserCount.setText(Search.bringCounts("academicUsers") + "");
        jTextField_adminUserCount.setText(Search.bringCounts("adminUsers") + "");
        jTextField_normalUserCount.setText(Search.bringCounts("normalUsers") + "");
        jTextField_bookReserved.setText(Search.bringCounts("reservedBooks") + "");
        jTextField_bookLost.setText(Search.bringCounts("lostBooks") + "");
    

    }//GEN-LAST:event_jButton_bringIstatisticsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_bringIstatistics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel_options;
    private javax.swing.JTextField jTextField_academicUserCount;
    private javax.swing.JTextField jTextField_adminUserCount;
    private javax.swing.JTextField jTextField_bookAvailable;
    private javax.swing.JTextField jTextField_bookBorrowed;
    private javax.swing.JTextField jTextField_bookLost;
    private javax.swing.JTextField jTextField_bookReserved;
    private javax.swing.JTextField jTextField_normalUserCount;
    private javax.swing.JTextField jTextField_totalUser;
    private javax.swing.JTextField jTextField_totalbook;
    // End of variables declaration//GEN-END:variables
}
